### PR TITLE
feat: highlight multiple words

### LINKED ISSUE #39: Highlight Words
I tried to highlight multiple words like this:

```
```sh /"Nenad Novakovic"|"dvlden@users.noreply.github.com"/
```

And also like this:

```
```sh /"Nenad Novakovic"/ /"dvlden@users.noreply.github.com"/
```

But neither approach has worked. In the docs, I saw an example with a single word only. Is this not a possibility yet and may I know if the regex going to be an option?

Good day!

### PR DESCRIPTION
**Pull request by ttwrpz**
Now, you have ability to do multiple word highlighting with:

````md
```text /carrot/1-5 /potato/1,3 /apple/

```
````

### CODE REVIEW

**Comment by atomiks** [comment]
Tests are failing (they aren't running on CI atm)

Screen Shot 2022-10-05 at 11 03 15 pm

**Comment by EpicEmeraldPlayz** [comment]
I'm so sorry. Let's me investigate the issues.

**Comment by EpicEmeraldPlayz** [comment]
All test cases are now fixed

**Comment by EpicEmeraldPlayz** [comment]
@atomiks Should I add the regex support for this one too? And change the regex of single word to

````
```text /"carrot"/1-5 /"potato"/1,3 /"apple"/

```
````

**Comment by atomiks** [comment]
Sorry @ttwrpz I will take a look at this in a second 💙

**Comment by atomiks** [comment]
It appears to work nicely, thank you so much for your work on this!

**Pull request merged**
