### PR TITLE
do not bundle dependencies, mark them as external

### PR DESCRIPTION
**Pull request by B2o5T**
## before
image

## after
image

why https://rikki.dev/posts/npm-libraries-should-not-bundle-dependencies

### CODE REVIEW

**Comment by atomiks** [comment]
This was needed to support CJS since those packages are ESM-only

**Comment by B2o5T** [comment]
any particular reason to support cjs in this case, when almost every remark/rehype plugin is esm only?

**Comment by atomiks** [comment]
Next.js was requiring it in Dec 2021 when I first made this, right? Some people are still using CJS to date though, as I accidentally forgot to bundle a dependency after a change and an issue was filed a couple of months ago.

**Comment by B2o5T** [comment]
You can use next.config.mjs or type:module in package.json and next.config.js

https://github.com/shuding/nextra/issues/1356

**Comment by muningis** [comment]
Why not have CJS and ESM outputs? https://antfu.me/posts/publish-esm-and-cjs

**Comment by atomiks** [comment]
@muningis this library has always had that. The problem is the dependencies of this library do not (they are ESM-only). For it to work, all imports need to do it.

**Comment by atomiks** [comment]
Merging with the migration to Shikiji

**Pull request merged**
