### PR TITLE
fix unexpected highlight words for custom meta properties

### PR DESCRIPTION
**Pull request by B2o5T**
use better regex 
image
fixes https://github.com/atomiks/rehype-pretty-code/issues/52

### CODE REVIEW

**Comment by atomiks** [comment]
One of the tests is failing
Screenshot 2022-12-26 at 2 09 54 pm

**Comment by B2o5T** [comment]
Thx, will fix later today

**Comment by atomiks** [comment]
@B2o5T feel free to just check for `filename` manually for now if need be. I know others might use something other than `title`/`filename`, but the library does intentionally use `title="..."` only so new wrappers should likely only use that.

**Comment by B2o5T** [comment]
Sorry for not finishing a fix, just was struggling with regex, found some workaround with skip/fail but js regex doesn’t support it

https://regex101.com/r/heqsZS/1

**Comment by atomiks** [comment]
https://github.com/atomiks/rehype-pretty-code/pull/58

**Pull request closed without merging**
