### PR TITLE
fix: support multi-word languages

### PR DESCRIPTION
**Pull request by silvenon**
There are some languages supported by shiki that have multiple words, separated by hyphens, like `git-rebase` and `vue-html`.

https://github.com/shikijs/shiki/blob/main/docs/languages.md

### CODE REVIEW

**Comment by atomiks** [comment]
Do you think we should fallback to `?? 'text'` if there was no lang specified? (rather than passing `undefined` as the shiki lang)

**Comment by atomiks** [comment]
@silvenon wondering if you want to do that in this PR or a new one? (if former, I'll merge this)

**Comment by silvenon** [comment]
Merge this, I'll do that in the next one.

**Comment by atomiks** [comment]
@silvenon based on the check for `language-` (from the other shiki package) the highlighting doesn't occur at all which I guess makes sense. I think we can just leave it. Released 0.0.6 with your PRs.

**Comment by silvenon** [comment]
I wanted to highlight some lines myself and it didn't occur to me to add `text` grammar, so I'll think about this problem some more to at least throw some helpful error if someone else tries to do the same.

**Comment by silvenon** [comment]
0.0.6 is a lower version than the prior 0.1.0, was that on purpose?

**Comment by atomiks** [comment]
Prior was 0.0.5 for the new package name, I started from 0.0.1

**Comment by silvenon** [comment]
Oh right, I didn't look at the diff 🤦  Changing names is confusing 😅  (But totally the right choice here.)

**Pull request merged**
