### PR TITLE
feat: CSS variable line numbers length

### LINKED ISSUE #62: Line numbers length
Add line numbers length to CSS variable can create dynamic line numbers width.

```diff
code > .line::before {
  counter-increment: line;
  content: counter(line);
 
  /* Other styling */
  display: inline-block;
-  width: 1rem;
+  width: calc(var(--line-numbers-length) * 1rem);
  margin-right: 2rem;
  text-align: right;
  color: gray;
}
```

### PR DESCRIPTION
**Pull request by anasrar**
close #62

### CODE REVIEW

**Comment by anasrar** [comment]
current behavior will add CSS variable `--line-numbers-length` if `showLineNumbers` is present

**Comment by atomiks** [comment]
Shouldn't it be `width` not `length`? 

I'm fine with adding this btw, just wondering if you have a concrete use case where you need the width to be different for certain code blocks?

**Comment by anasrar** [comment]
> just wondering if you have a concrete use case where you need the width to be different based on the number of lines there are? Or is there a more obvious style where it should be used?

just nice to have you can dynamically set the width base on line numbers, mostly on markdown just some snippet that have few lines of code, but when have lot of lines of code a little bit odd having fix width line numbers.

**Comment by atomiks** [comment]
Is this because `100` takes up much more space than `1`, so you need to make it wider when there's more digits?

**Comment by atomiks** [comment]
I'm going to merge this and rename it as `lineNumbersMaxDigits` as I think it's a bit less confusing, I didn't know what `length` meant originally. Thank you for the contribution!

**Comment by anasrar** [comment]
> I'm going to merge this and rename it as lineNumbersMaxDigits as I think it's a bit less confusing, I didn't know what length meant originally.

Sure, why not.

> Thank you for the contribution!

You welcome.

**Pull request merged**
